import { InitialReducerStateType, Todos } from "../Utils/types";

export const initialState: InitialReducerStateType = {
  todoList: [] as Todos,
};

export const actions = {
  FETCH_TODO_ITEM: "FETCH_TODO_ITEM",
  ADD_TODO_ITEM: "ADD_TODO_ITEM",
  EDIT_TODO_ITEM: "EDIT_TODO_ITEM",
  REMOVE_TODO_ITEM: "REMOVE_TODO_ITEM",
  PERMANENTLY_REMOVE_TODO_ITEM: "PERMANENTLY_REMOVE_TODO_ITEM",
  RESTORE_TODO_ITEM: "RESTORE_TODO_ITEM",
  TOGGLE_COMPLETED: "TOGGLE_COMPLETED",
  ARCHIVE_TODO_ITEM: "ARCHIVE_TODO_ITEM",
  ADD_LABEL_TO_TODO_ITEM: "ADD_LABEL_TO_TODO_ITEM",
  REMOVE_LABEL_FROM_TODO_ITEM: "REMOVE_LABEL_FROM_TODO_ITEM",
};
